/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author alex
 */
public class CierreDiario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CierreDiario.class.getName());

    /**
     * Creates new form CierreDiario
     */
    public CierreDiario() {
        initComponents();
        setLocationRelativeTo(null);
        
        java.time.format.DateTimeFormatter f = java.time.format.DateTimeFormatter.ofPattern("d/M/yyyy");

        String hoy = java.time.LocalDate.now().format(f);

        txtFechaHoy.setText(hoy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFechaHoy = new javax.swing.JTextField();
        btnEjecutar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResumen = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cierre Diario");

        jLabel2.setText("Fecha");

        txtFechaHoy.setEditable(false);

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(this::btnEjecutarActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        tblResumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResumen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEjecutar)))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(txtFechaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnEjecutar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        String hoy = txtFechaHoy.getText().trim();

        if (hoy.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo obtener la fecha actual.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        int cerrados = data.CabeceraArchivo.cerrarPorFecha(hoy);

        javax.swing.JOptionPane.showMessageDialog(this,
                "Documentos cerrados hoy (" + hoy + "): " + cerrados,
                "Cierre Diario",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Mostrar SOLO cuentas con movimientos del día
        cargarMovimientosDelDia(hoy);
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void cargarMovimientosDelDia(String fecha) {

        // 1) Leer cabeceras y detalles
        java.util.List<model.CabeceraTransaccion> cabeceras = data.CabeceraArchivo.cargarTodos();
        java.util.List<model.DetalleTransaccion> detalles = data.DetalleArchivo.cargarTodos();
        java.util.List<model.CuentaContable> catalogo = data.CuentaArchivo.cargarTodas();

        // 2) Documentos que son exactamente de esa fecha
        java.util.Set<String> docsDelDia = new java.util.HashSet<>();
        for (model.CabeceraTransaccion c : cabeceras) {
            if (fecha.equals(c.getFechaDocu())) {
                docsDelDia.add(c.getNroDocu());
            }
        }

        // 3) Acumular débitos y créditos por cuenta SOLO de esos documentos
        java.util.Map<String, Double> debitos = new java.util.HashMap<>();
        java.util.Map<String, Double> creditos = new java.util.HashMap<>();

        for (model.DetalleTransaccion d : detalles) {
            if (!docsDelDia.contains(d.getNroDoc())) continue;

            String cuenta = d.getCuentaContable();
            debitos.merge(cuenta, d.getValorDebito(), Double::sum);
            creditos.merge(cuenta, d.getValorCredito(), Double::sum);
        }

        // 4) Tabla SOLO con cuentas que se movieron ese día
        String[] cols = { "No. Cuenta", "Descripción", "Débito", "Crédito", "Saldo" };

        javax.swing.table.DefaultTableModel modelo =
                new javax.swing.table.DefaultTableModel(cols, 0) {
                    @Override
                    public boolean isCellEditable(int r, int c) { return false; }
                };

        double totalDeb = 0.0;
        double totalCre = 0.0;

        for (String nroCuenta : debitos.keySet()) {
            double deb = debitos.getOrDefault(nroCuenta, 0.0);
            double cre = creditos.getOrDefault(nroCuenta, 0.0);
            double saldo = deb - cre;

            totalDeb += deb;
            totalCre += cre;

            String descripcion = "";
            for (model.CuentaContable c : catalogo) {
                if (c.getNumero().equals(nroCuenta)) {
                    descripcion = c.getDescripcion();
                    break;
                }
            }

            modelo.addRow(new Object[]{ nroCuenta, descripcion, deb, cre, saldo });
        }

        // Fila de totales
        modelo.addRow(new Object[]{ "TOTALES", "", totalDeb, totalCre, (totalDeb - totalCre) });

        tblResumen.setModel(modelo);
    }



    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CierreDiario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResumen;
    private javax.swing.JTextField txtFechaHoy;
    // End of variables declaration//GEN-END:variables
}
