/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author alex
 */
public class CierreDiario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CierreDiario.class.getName());

    /**
     * Creates new form CierreDiario
     */
    public CierreDiario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDesde = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHasta = new javax.swing.JTextField();
        btnEjecutar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResumen = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cierre Diario");

        jLabel2.setText("Desde");

        jLabel3.setText("Hasta");

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(this::btnEjecutarActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        tblResumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResumen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEjecutar)))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(btnEjecutar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        String desde = txtDesde.getText().trim();
        String hasta = txtHasta.getText().trim();

        if (desde.isEmpty() || hasta.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe digitar las fechas Desde y Hasta.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Ejecutamos el cierre (marca estatus en las cabeceras)
        int cerrados = data.CabeceraArchivo.cerrarPorRangoFechas(desde, hasta);

        javax.swing.JOptionPane.showMessageDialog(this,
                "Documentos cerrados: " + cerrados,
                "Cierre Diario",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Mostrar SOLO cuentas que movieron algo
        cargarMovimientosDelRango(desde, hasta);
    }//GEN-LAST:event_btnEjecutarActionPerformed

    /**
    * Muestra en tblResumen TODO el catálogo de cuentas
    * y los débitos/créditos que ha tenido cada cuenta
    * en el rango de fechas indicado.
    */
   private void cargarResumenRango(String desde, String hasta) {

       DateTimeFormatter f = DateTimeFormatter.ofPattern("d/M/yyyy");
       LocalDate d1 = LocalDate.parse(desde, f);
       LocalDate d2 = LocalDate.parse(hasta, f);

       // 1) Cargar cabeceras y detalles
       List<model.CabeceraTransaccion> cabeceras = data.CabeceraArchivo.cargarTodos();
       List<model.DetalleTransaccion> detalles = data.DetalleArchivo.cargarTodos();
       List<model.CuentaContable> catalogo = data.CuentaArchivo.cargarTodas();

       // 2) Determinar qué documentos están dentro del rango
       Set<String> documentosEnRango = new HashSet<>();
       for (model.CabeceraTransaccion c : cabeceras) {
           LocalDate fechaDoc = LocalDate.parse(c.getFechaDocu(), f);
           if (!fechaDoc.isBefore(d1) && !fechaDoc.isAfter(d2)) {
               documentosEnRango.add(c.getNroDocu());
           }
       }

       // 3) Acumular débitos y créditos por cuenta SOLO de esos documentos
       Map<String, Double> debitos = new HashMap<>();
       Map<String, Double> creditos = new HashMap<>();

       for (model.DetalleTransaccion d : detalles) {
           if (!documentosEnRango.contains(d.getNroDoc())) {
               continue;
           }
           String cta = d.getCuentaContable();    // ajusta nombre si tu getter es distinto
           debitos.merge(cta, d.getValorDebito(), Double::sum);
           creditos.merge(cta, d.getValorCredito(), Double::sum);
       }

       // 4) Construir el modelo de la tabla usando TODO el catálogo
       String[] columnas = {
           "No. Cuenta", "Descripción",
           "Débito periodo", "Crédito periodo", "Saldo periodo"
       };

       DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
           @Override
           public boolean isCellEditable(int row, int column) {
               return false;
           }
       };

       for (model.CuentaContable cta : catalogo) {
           String numero = cta.getNumero();
           String desc   = cta.getDescripcion();

           double deb = debitos.getOrDefault(numero, 0.0);
           double cre = creditos.getOrDefault(numero, 0.0);
           double saldo = deb - cre; // saldo del periodo

           Object[] fila = {
               numero,
               desc,
               deb,
               cre,
               saldo
           };
           modelo.addRow(fila);
       }

       tblResumen.setModel(modelo);
   }
   
   private void cargarMovimientosDelRango(String desde, String hasta) {

        DateTimeFormatter f = DateTimeFormatter.ofPattern("d/M/yyyy");
        LocalDate d1 = LocalDate.parse(desde, f);
        LocalDate d2 = LocalDate.parse(hasta, f);

        // 1) Leer cabeceras y detalles
        List<model.CabeceraTransaccion> cabeceras = data.CabeceraArchivo.cargarTodos();
        List<model.DetalleTransaccion> detalles = data.DetalleArchivo.cargarTodos();
        List<model.CuentaContable> catalogo = data.CuentaArchivo.cargarTodas();

        // 2) Filtrar documentos que están dentro del rango
        Set<String> docsEnRango = new HashSet<>();
        for (model.CabeceraTransaccion c : cabeceras) {
            LocalDate fecha = LocalDate.parse(c.getFechaDocu(), f);
            if (!fecha.isBefore(d1) && !fecha.isAfter(d2)) {
                docsEnRango.add(c.getNroDocu());
            }
        }

        // 3) Acumular débitos y créditos SOLO para cuentas con movimientos
        Map<String, Double> debitos = new HashMap<>();
        Map<String, Double> creditos = new HashMap<>();

        for (model.DetalleTransaccion d : detalles) {
            if (!docsEnRango.contains(d.getNroDoc())) continue;

            String cuenta = d.getCuentaContable();

            debitos.merge(cuenta, d.getValorDebito(), Double::sum);
            creditos.merge(cuenta, d.getValorCredito(), Double::sum);
        }

        // 4) Construir tabla SOLO con cuentas que se movieron
        String[] cols = { "No. Cuenta", "Descripción", "Débito", "Crédito", "Saldo" };
        DefaultTableModel modelo = new DefaultTableModel(cols, 0) {
            @Override
            public boolean isCellEditable(int r, int c) { return false; }
        };

        for (String nroCuenta : debitos.keySet()) {
            double deb = debitos.getOrDefault(nroCuenta, 0.0);
            double cre = creditos.getOrDefault(nroCuenta, 0.0);
            double saldo = deb - cre;

            // Encontrar la cuenta en el catálogo
            String descripcion = "";
            for (model.CuentaContable c : catalogo) {
                if (c.getNumero().equals(nroCuenta)) {
                    descripcion = c.getDescripcion();
                    break;
                }
            }

            modelo.addRow(new Object[]{
                nroCuenta,
                descripcion,
                deb,
                cre,
                saldo
            });
        }

        tblResumen.setModel(modelo);
    }


    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CierreDiario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResumen;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtHasta;
    // End of variables declaration//GEN-END:variables
}
