/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

/**
 *
 * @author alex
 */
public class ConsultaCatalogoCuentas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaCatalogoCuentas.class.getName());

    /**
     * Creates new form ConsultaCatalogoCuentas
     */
    public ConsultaCatalogoCuentas() {
        initComponents();
        setLocationRelativeTo(null);
        rbNumero.setSelected(true); // por defecto
        cargarTablaTodos();  
    }
    
    // Mostrar TODO el catálogo
    private void cargarTablaTodos() {
        java.util.List<model.CuentaContable> lista =
                data.CuentaArchivo.cargarTodas();

        construirModeloTabla(lista);
    }

    // Filtrar por número de cuenta (comienza con...)
    private void cargarTablaPorNumero(String nroParcial) {
        java.util.List<model.CuentaContable> listaOriginal =
                data.CuentaArchivo.cargarTodas();

        java.util.List<model.CuentaContable> filtrada = new java.util.ArrayList<>();
        for (model.CuentaContable c : listaOriginal) {
            if (String.valueOf(c.getNumero()).startsWith(nroParcial)) {
                filtrada.add(c);
            }
        }
        construirModeloTabla(filtrada);
    }

    // Filtrar por descripción (contiene el texto)
    private void cargarTablaPorDescripcion(String texto) {
        java.util.List<model.CuentaContable> listaOriginal =
                data.CuentaArchivo.cargarTodas();

        java.util.List<model.CuentaContable> filtrada = new java.util.ArrayList<>();
        String t = texto.toLowerCase();

        for (model.CuentaContable c : listaOriginal) {
            if (c.getDescripcion().toLowerCase().contains(t)) {
                filtrada.add(c);
            }
        }
        construirModeloTabla(filtrada);
    }

    // Construye el modelo de la tabla a partir de la lista
    private void construirModeloTabla(java.util.List<model.CuentaContable> lista) {
        String[] columnas = {
            "No. Cuenta", "Descripción", "Tipo", "Nivel",
            "Cuenta Padre", "Grupo"
        };

        javax.swing.table.DefaultTableModel modelo =
                new javax.swing.table.DefaultTableModel(columnas, 0) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false; // solo lectura
                    }
                };

        for (model.CuentaContable c : lista) {

            String tipoTxt = c.getTipo().equalsIgnoreCase("G")
                    ? "General" : "Detalle";

            Object[] fila = {
                c.getNumero(),
                c.getDescripcion(),
                tipoTxt,
                c.getNivel(),
                c.getPadre(),
                c.getGrupo()
            };
            modelo.addRow(fila);
        }

        tblCuentas.setModel(modelo);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpFiltro = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        rbNumero = new javax.swing.JRadioButton();
        rbDescripcion = new javax.swing.JRadioButton();
        btnCargar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuentas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta Catalogo Cuentas");

        jLabel2.setText("Buscar");

        grpFiltro.add(rbNumero);
        rbNumero.setText("Por numero");

        grpFiltro.add(rbDescripcion);
        rbDescripcion.setText("Por descripcion");

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(this::btnCargarActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        tblCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCuentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(btnCargar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(rbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNumero)
                    .addComponent(rbDescripcion))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        String filtro = txtFiltro.getText().trim();

        // Buscar por número
        if (rbNumero.isSelected()) {
            if (filtro.isEmpty()) {
                cargarTablaTodos();
            } else {
                cargarTablaPorNumero(filtro);
            }

            // limpiar filtro y radios si quieres
            txtFiltro.setText("");
            grpFiltro.clearSelection();
            return;
        }

        // Buscar por descripción
        if (rbDescripcion.isSelected()) {
            if (filtro.isEmpty()) {
                cargarTablaTodos();
            } else {
                cargarTablaPorDescripcion(filtro);
            }

            txtFiltro.setText("");
            grpFiltro.clearSelection();
            return;
        }

        // Si ningún radio está seleccionado → mostrar todo
        cargarTablaTodos();
        txtFiltro.setText("");
    }//GEN-LAST:event_btnCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultaCatalogoCuentas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.ButtonGroup grpFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbDescripcion;
    private javax.swing.JRadioButton rbNumero;
    private javax.swing.JTable tblCuentas;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
