/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

/**
 *
 * @author alex
 */
public class ConsultaCabeceras extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaCabeceras.class.getName());

    /**
     * Creates new form ConsultaCabeceras
     */
    public ConsultaCabeceras() {
        initComponents();
        setLocationRelativeTo(null);
        cargarTablaTodos(); 
    }
    
    // Importa arriba si hace falta:
    // import java.util.List;

    private void cargarTablaTodos() {
        java.util.List<model.CabeceraTransaccion> lista =
                data.CabeceraArchivo.cargarTodos();
        construirModeloTabla(lista);
    }

    private void cargarTablaPorFecha(String fecha) {
        java.util.List<model.CabeceraTransaccion> lista =
                data.CabeceraArchivo.cargarPorFecha(fecha);
        construirModeloTabla(lista);
    }

    private void cargarTablaPorRango(String desde, String hasta) {
        java.util.List<model.CabeceraTransaccion> lista =
                data.CabeceraArchivo.cargarPorRango(desde, hasta);
        construirModeloTabla(lista);
    }

    private void cargarTablaPorTipo(int tipoDoc) {
        java.util.List<model.CabeceraTransaccion> lista =
                data.CabeceraArchivo.cargarPorTipo(tipoDoc);
        construirModeloTabla(lista);
    }

    /**
     * Construye el modelo de la tabla con la lista recibida
     */
    private void construirModeloTabla(java.util.List<model.CabeceraTransaccion> lista) {
        String[] columnas = {
            "Nro Doc", "Fecha", "Tipo", "Descripción",
            "Hecho por", "Monto", "Fecha Actualización", "Status"
        };

        javax.swing.table.DefaultTableModel modelo =
                new javax.swing.table.DefaultTableModel(columnas, 0) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false; // solo lectura
                    }
                };

        for (model.CabeceraTransaccion c : lista) {

            String tipoTxt;
            switch (c.getTipoDocu()) {
                case 1 -> tipoTxt = "Factura";
                case 2 -> tipoTxt = "Nota Débito";
                case 3 -> tipoTxt = "Nota Crédito";
                default -> tipoTxt = String.valueOf(c.getTipoDocu());
            }

            Object[] fila = {
                c.getNroDocu(),
                c.getFechaDocu(),
                tipoTxt,
                c.getDescripcion(),
                c.getHechoPor(),
                c.getMontoTransaccion(),
                c.getFechaActualizacion(),
                c.isStatusActualizacion() ? "Actualizado" : "Pendiente"
            };
            modelo.addRow(fila);
        }

        tblCabeceras.setModel(modelo);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpFiltro = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        rbFecha = new javax.swing.JRadioButton();
        rbRango = new javax.swing.JRadioButton();
        txtDesde = new javax.swing.JTextField();
        txtHasta = new javax.swing.JTextField();
        rbTipoDoc = new javax.swing.JRadioButton();
        cbTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCabeceras = new javax.swing.JTable();
        btnTodos = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consultas Cabecera");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Filtros");

        grpFiltro.add(rbFecha);
        rbFecha.setText("Fecha");

        grpFiltro.add(rbRango);
        rbRango.setText("Rango");
        rbRango.addActionListener(this::rbRangoActionPerformed);

        grpFiltro.add(rbTipoDoc);
        rbTipoDoc.setText("Tipo Documento");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Factura", "Nota Debito", "Nota Credito" }));

        tblCabeceras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCabeceras);

        btnTodos.setText("Limpiar Filtro");
        btnTodos.addActionListener(this::btnTodosActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        btnCargar.setText("Filtrar");
        btnCargar.addActionListener(this::btnCargarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rbFecha)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(56, 56, 56)
                                            .addComponent(rbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnCargar))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(btnTodos))))
                                .addComponent(rbRango, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbFecha)
                    .addComponent(rbTipoDoc)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbRango)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTodos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRangoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRangoActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        cargarTablaTodos();
    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void limpiarCampos() {
        txtFecha.setText("");
        txtDesde.setText("");
        txtHasta.setText("");
        cbTipo.setSelectedIndex(0);

        // Opcional: seleccionar automáticamente la opción "Todos"
        // rbTodos.setSelected(true);
    }

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // 🔹 1) Filtro por FECHA
        if (rbFecha.isSelected()) {
            String fecha = txtFecha.getText().trim();

            if (fecha.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Debe digitar una fecha.",
                        "Validación",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            cargarTablaPorFecha(fecha);
            limpiarCampos();
            return;
        }

        // 🔹 2) Filtro por RANGO DE FECHAS
        if (rbRango.isSelected()) {
            String desde = txtDesde.getText().trim();
            String hasta = txtHasta.getText().trim();

            if (desde.isEmpty() || hasta.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Debe digitar las fechas Desde y Hasta.",
                        "Validación",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            cargarTablaPorRango(desde, hasta);
            limpiarCampos();
            return;
        }

        // 🔹 3) Filtro por TIPO DE DOCUMENTO
        if (rbTipoDoc.isSelected()) {
            int idx = cbTipo.getSelectedIndex();

            if (idx <= 0) { 
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Debe seleccionar un Tipo de Documento.",
                        "Validación",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            int tipoDoc = switch (idx) {
                case 1 -> 1; // Factura
                case 2 -> 2; // Nota Débito
                case 3 -> 3; // Nota Crédito
                default -> 0;
            };

            cargarTablaPorTipo(tipoDoc);
            limpiarCampos();
            return;
        }

        // 🔹 4) Si no hay nada seleccionado, mostramos TODO
        cargarTablaTodos();
    }//GEN-LAST:event_btnCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultaCabeceras().setVisible(true));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnTodos;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.ButtonGroup grpFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbFecha;
    private javax.swing.JRadioButton rbRango;
    private javax.swing.JRadioButton rbTipoDoc;
    private javax.swing.JTable tblCabeceras;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHasta;
    // End of variables declaration//GEN-END:variables
}
