/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;


public class MantenimientoCuentas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantenimientoCuentas.class.getName());

    /**
     * Creates new form MantenimientoCuentas
     */
    public MantenimientoCuentas() {
        initComponents();
        setLocationRelativeTo(null);
        cargarTablaCuentas();
    }
    
    private void limpiarCampos() {
    txtNumero.setText("");
    txtDescripcion.setText("");
    cbTipo.setSelectedIndex(0);
    txtNivel.setText("");
    txtPadre.setText("");
    cbGrupo.setSelectedIndex(0);
    txtNumero.requestFocus();
    txtNumero.setEnabled(true);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbGrupo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNivel = new javax.swing.JTextField();
        txtPadre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuentas = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mantenimiento de Cuentas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numero de Cuenta");

        txtNumero.addActionListener(this::txtNumeroActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripcion");

        txtDescripcion.addActionListener(this::txtDescripcionActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo Cuenta");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "General", "Detalle" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Grupo");

        cbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Activo", "Pasivo", "Capital", "Ingresos", "Gastos" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nivel");

        txtNivel.addActionListener(this::txtNivelActionPerformed);

        txtPadre.addActionListener(this::txtPadreActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cuenta Padre");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(255, 51, 51));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCuentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCuentas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)
                                    .addComponent(txtDescripcion)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(315, 315, 315)
                                        .addComponent(btnBuscar))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCerrar))))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLimpiar))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscar)
                                        .addGap(7, 7, 7))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel6))))
                    .addComponent(btnGuardar))
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNivelActionPerformed

    private void txtPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPadreActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String numero = txtNumero.getText().trim();
        String descripcion = txtDescripcion.getText().trim();
        String nivelTxt = txtNivel.getText().trim();
        String padre = txtPadre.getText().trim();
        String tipoTexto = (String) cbTipo.getSelectedItem();
        String grupo = (String) cbGrupo.getSelectedItem();

        // Validaciones básicas
        if (numero.isEmpty() || descripcion.isEmpty() || nivelTxt.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Número, Descripción y Nivel son obligatorios.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int nivel;
        try {
            nivel = Integer.parseInt(nivelTxt);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El Nivel debe ser numérico.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Convertir tipo
        String tipo;
        if ("General".equalsIgnoreCase(tipoTexto)) {
            tipo = "G";
        } else {
            tipo = "D";
        }

        model.CuentaContable existente = data.CuentaArchivo.buscarPorNumero(numero);

        // ===============================
        // CREAR NUEVA CUENTA
        // ===============================
        if (existente == null) {

            model.CuentaContable nueva = new model.CuentaContable(
                    numero,
                    descripcion,
                    tipo,
                    nivel,
                    padre,
                    grupo
            );

            boolean ok = data.CuentaArchivo.agregar(nueva);

            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Cuenta creada correctamente.",
                        "Información",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se pudo crear la cuenta.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            return;
        }

        // ===============================
        // MODIFICAR CUENTA EXISTENTE
        // ===============================

        // ❌ Regla CLAVE: NO modificar cuentas generales
        if (!"D".equalsIgnoreCase(existente.getTipo())) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se puede modificar una cuenta GENERAL.\n"
                  + "Solo las cuentas DETALLE pueden modificarse.",
                    "Restricción",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        model.CuentaContable modificada = new model.CuentaContable(
                numero,
                descripcion,
                tipo,
                nivel,
                padre,
                grupo,
                existente.getDebitoAcum(),
                existente.getCreditoAcum(),
                existente.getBalance()
        );

        boolean ok = data.CuentaArchivo.actualizar(modificada);

        if (ok) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Cuenta modificada correctamente.",
                    "Información",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
            txtNumero.setEnabled(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo modificar la cuenta.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    private void cargarTablaCuentas() {
        java.util.List<model.CuentaContable> lista = data.CuentaArchivo.cargarTodas();

        String[] cols = { "No. Cuenta", "Descripción", "Tipo", "Nivel", "Padre", "Grupo" };

        javax.swing.table.DefaultTableModel modelo =
                new javax.swing.table.DefaultTableModel(cols, 0) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };

        for (model.CuentaContable c : lista) {
            String tipoTxt = c.getTipo().equalsIgnoreCase("G") ? "GENERAL" : "DETALLE";

            modelo.addRow(new Object[]{
                c.getNumero(),
                c.getDescripcion(),
                tipoTxt,
                c.getNivel(),
                c.getPadre(),
                c.getGrupo()
            });
        }

        tblCuentas.setModel(modelo);
    }

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tblCuentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCuentasMouseClicked
        if (evt.getClickCount() != 2) return;

        int fila = tblCuentas.getSelectedRow();
        if (fila < 0) return;

        String numero = String.valueOf(tblCuentas.getValueAt(fila, 0));

        model.CuentaContable c = data.CuentaArchivo.buscarPorNumero(numero);
        if (c == null) return;

        // Llenar campos
        txtNumero.setText(c.getNumero());
        txtDescripcion.setText(c.getDescripcion());
        txtNivel.setText(String.valueOf(c.getNivel()));
        txtPadre.setText(c.getPadre());
        cbGrupo.setSelectedItem(c.getGrupo());
        
        // Tipo (ajusta según tu ComboBox)
        if ("G".equalsIgnoreCase(c.getTipo())) {
            cbTipo.setSelectedItem("GENERAL");
        } else {
            cbTipo.setSelectedItem("DETALLE");
        }

        // Recomendado: bloquear número para evitar cambiar la llave primaria
        txtNumero.setEnabled(false);
    }//GEN-LAST:event_tblCuentasMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String numero = txtNumero.getText().trim();

        if (numero.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe escribir el No. de Cuenta para buscar.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            txtNumero.requestFocus();
            return;
        }

        model.CuentaContable c = data.CuentaArchivo.buscarPorNumero(numero);

        // Si NO existe => permitir crear
        if (c == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La cuenta NO existe. Puede crearla.",
                    "Información",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            limpiarCamposExceptoNumero();

            // Para creación: permitir edición y permitir escribir número
            txtNumero.setEnabled(true);
            setEdicionHabilitada(true);

            txtDescripcion.requestFocus();
            return;
        }

        // Si existe => llenar campos
        txtDescripcion.setText(c.getDescripcion());
        txtNivel.setText(String.valueOf(c.getNivel()));
        txtPadre.setText(c.getPadre());

        String tipo = c.getTipo();
        if (tipo != null) tipo = tipo.trim().toUpperCase();

        if ("G".equals(tipo)) {
            cbTipo.setSelectedItem("General");   // ajusta si tu combo usa otro texto
        } else if ("D".equals(tipo)) {
            cbTipo.setSelectedItem("Detalle");   // ajusta si tu combo usa otro texto
        } else {
            cbTipo.setSelectedItem(tipo);
        }

        cbGrupo.setSelectedItem(c.getGrupo());

        // REGLA: Solo se pueden modificar cuentas DETALLE
        if (!"D".equalsIgnoreCase(tipo)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Esta cuenta es GENERAL. No se permite modificar.\n"
                  + "Solo se pueden modificar cuentas DETALLE.",
                    "Restricción",
                    javax.swing.JOptionPane.WARNING_MESSAGE);

            // Bloquear edición, pero permitir buscar otra
            setEdicionHabilitada(false);
            txtNumero.setEnabled(true);
            txtNumero.requestFocus();
            return;
        }

        // Si es detalle => sí se puede editar
        javax.swing.JOptionPane.showMessageDialog(this,
                "Cuenta DETALLE encontrada. Puede modificar y guardar.",
                "Información",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        setEdicionHabilitada(true);

        // En modificación: no permitir cambiar el número
        txtNumero.setEnabled(false);
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    private void limpiarCamposExceptoNumero() {
        txtDescripcion.setText("");
        txtNivel.setText("");
        txtPadre.setText("");
        if (cbTipo.getItemCount() > 0) cbTipo.setSelectedIndex(0);
        if (cbGrupo.getItemCount() > 0) cbGrupo.setSelectedIndex(0);
    }
    
    private void setEdicionHabilitada(boolean habilitar) {
        //NO incluyo txtNumero aquí porque lo controlamos aparte
        txtDescripcion.setEnabled(habilitar);
        cbTipo.setEnabled(habilitar);
        txtNivel.setEnabled(habilitar);
        txtPadre.setEnabled(habilitar);
        cbGrupo.setEnabled(habilitar);

        btnGuardar.setEnabled(habilitar);
        // btnEliminar si tienes, también:
        // btnEliminar.setEnabled(habilitar);
    }

    private boolean esDetalle(model.CuentaContable c) {
        return c != null && c.getTipo() != null && c.getTipo().trim().equalsIgnoreCase("D");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MantenimientoCuentas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbGrupo;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCuentas;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPadre;
    // End of variables declaration//GEN-END:variables
}
