/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;


public class MovimientoTransacciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MovimientoTransacciones.class.getName());

    /**
     * Creates new form MovimientoTransacciones
     */
    public MovimientoTransacciones() {
        initComponents();
        setLocationRelativeTo(null); // centrar
    }
    
    private void actualizarAreaDetalles(String nroDocu) {
    java.util.List<model.DetalleTransaccion> detalles =
            data.DetalleArchivo.cargarPorDocumento(nroDocu);

    StringBuilder sb = new StringBuilder();
    for (model.DetalleTransaccion d : detalles) {
        sb.append(String.format("%s | %d | %s | D: %.2f | C: %.2f | %s%n",
                d.getNroDoc(),
                d.getSecuencia(),
                d.getCuentaContable(),
                d.getValorDebito(),
                d.getValorCredito(),
                d.getComentario()));
    }
    txtDetalles.setText(sb.toString());
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNroDocu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbTipoDocu = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHechoPor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDebito = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCredito = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextArea();
        btnAgregarDetalle = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        txtComentario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movimiento Transacciones");

        jLabel2.setText("Nro Documento");

        txtNroDocu.addActionListener(this::txtNroDocuActionPerformed);

        jLabel3.setText("Fecha");

        txtFecha.addActionListener(this::txtFechaActionPerformed);

        jLabel4.setText("Tipo Documento");

        cbTipoDocu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Factura", "Nota Debito", "Nota Credito" }));

        jLabel5.setText("Descripcion");

        jLabel6.setText("Hecho por");

        jLabel7.setText("Monto Total");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        jLabel8.setText("Cuenta Contable");

        jLabel9.setText("Debito");

        jLabel10.setText("Credito");

        jLabel11.setText("Comentario");

        txtDetalles.setColumns(20);
        txtDetalles.setRows(5);
        jScrollPane1.setViewportView(txtDetalles);

        btnAgregarDetalle.setText("Agregar Detalle");
        btnAgregarDetalle.setToolTipText("");
        btnAgregarDetalle.addActionListener(this::btnAgregarDetalleActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(txtNroDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(141, 141, 141))
                                    .addComponent(txtHechoPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbTipoDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                                .addComponent(btnGuardar)))))
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCuenta)
                                            .addComponent(txtDebito, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                            .addComponent(txtCredito)))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(270, 270, 270)
                                        .addComponent(btnAgregarDetalle))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnCerrar)
                                                .addGap(17, 17, 17)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNroDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHechoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnAgregarDetalle)
                        .addGap(26, 26, 26)
                        .addComponent(btnCerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(5, 5, 5)
                                .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtNroDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroDocuActionPerformed
        String nro = txtNroDocu.getText().trim();
        if (nro.isEmpty()) return;

        model.CabeceraTransaccion cab =
                data.CabeceraArchivo.buscarPorNumero(nro);

        if (cab == null) {
            // No existe, limpiar campos y permitir crear
            txtFecha.setText("");
            cbTipoDocu.setSelectedIndex(0);
            txtDescripcion.setText("");
            txtHechoPor.setText("");
            txtMonto.setText("");
            txtDetalles.setText("");
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Documento no existe. Puede crearlo.",
                    "Información",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (cab.isStatusActualizacion()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Transacción ha sido actualizada (cerrada). No se puede modificar.",
                        "Información",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
            }
            // Mostrar datos
            txtFecha.setText(cab.getFechaDocu());
            // mapear tipoDocu numérico a texto
            switch (cab.getTipoDocu()) {
                case 1 -> cbTipoDocu.setSelectedItem("Factura");
                case 2 -> cbTipoDocu.setSelectedItem("Nota Débito");
                case 3 -> cbTipoDocu.setSelectedItem("Nota Crédito");
                default -> cbTipoDocu.setSelectedIndex(0);
            }
            txtDescripcion.setText(cab.getDescripcion());
            txtHechoPor.setText(cab.getHechoPor());
            txtMonto.setText(String.valueOf(cab.getMontoTransaccion()));
            actualizarAreaDetalles(nro);
        }

    }//GEN-LAST:event_txtNroDocuActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
                                                  
        String nro = txtNroDocu.getText().trim();
        String fecha = txtFecha.getText().trim();
        String tipoTexto = (String) cbTipoDocu.getSelectedItem();
        String descripcion = txtDescripcion.getText().trim();
        String hechoPor = txtHechoPor.getText().trim();
        String montoTexto = txtMonto.getText().trim();

        if (nro.isEmpty() || fecha.isEmpty() || "Seleccione".equals(tipoTexto)
                || descripcion.isEmpty() || hechoPor.isEmpty() || montoTexto.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Todos los campos de cabecera son obligatorios.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int tipoDocu;
        if ("Factura".equals(tipoTexto)) {
            tipoDocu = 1;
        } else if ("Nota Débito".equals(tipoTexto)) {
            tipoDocu = 2;
        } else {
            tipoDocu = 3;
        }

        double monto;
        try {
            monto = Double.parseDouble(montoTexto);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El monto debe ser numérico.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        model.CabeceraTransaccion existente =
                data.CabeceraArchivo.buscarPorNumero(nro);

        String fechaActualizacion = fecha;   // por ahora usamos la misma
        boolean statusActualizacion = false; // aún no cerrada

        if (existente == null) {
            // Crear nueva
            model.CabeceraTransaccion nueva = new model.CabeceraTransaccion(
                    nro, fecha, tipoDocu, descripcion, hechoPor,
                    monto, fechaActualizacion, statusActualizacion);

            boolean ok = data.CabeceraArchivo.agregar(nueva);

            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Cabecera creada correctamente.",
                        "Información",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Ya existe una cabecera con ese número.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Modificar existente (si aún no está cerrada)
            if (existente.isStatusActualizacion()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "La transacción ya fue actualizada/cerrada. No se puede modificar.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            model.CabeceraTransaccion modificada = new model.CabeceraTransaccion(
                    nro, fecha, tipoDocu, descripcion, hechoPor,
                    monto, fechaActualizacion, statusActualizacion);

            boolean ok = data.CabeceraArchivo.actualizar(modificada);

            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Cabecera modificada correctamente.",
                        "Información",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se pudo actualizar la cabecera.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDetalleActionPerformed
                                                
        String nro = txtNroDocu.getText().trim();
        String cuenta = txtCuenta.getText().trim();
        String debitoTexto = txtDebito.getText().trim();
        String creditoTexto = txtCredito.getText().trim();
        String comentario = txtComentario.getText().trim();

        if (nro.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe indicar un Nro de documento primero.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (cuenta.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe indicar la cuenta contable.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar que la cuenta exista en el catálogo
        model.CuentaContable cta = data.CuentaArchivo.buscarPorNumero(cuenta);
        if (cta == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La cuenta contable no existe en el catálogo.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double debito = 0.0;
        double credito = 0.0;

        try {
            if (!debitoTexto.isEmpty()) {
                debito = Double.parseDouble(debitoTexto);
            }
            if (!creditoTexto.isEmpty()) {
                credito = Double.parseDouble(creditoTexto);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Débito y Crédito deben ser numéricos.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (debito == 0 && credito == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe indicar un valor en Débito o Crédito.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Determinar secuencia: cantidad de líneas + 1
        java.util.List<model.DetalleTransaccion> existentes =
                data.DetalleArchivo.cargarPorDocumento(nro);
        int secuencia = existentes.size() + 1;

        model.DetalleTransaccion det = new model.DetalleTransaccion(
                nro, secuencia, cuenta, debito, credito, comentario);

        boolean ok = data.DetalleArchivo.agregar(det);

        if (ok) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Detalle agregado.",
                    "Información",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            // limpiar campos de detalle
            txtCuenta.setText("");
            txtDebito.setText("");
            txtCredito.setText("");
            txtComentario.setText("");
            txtCuenta.requestFocus();

            actualizarAreaDetalles(nro);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo agregar el detalle.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarDetalleActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MovimientoTransacciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDetalle;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbTipoDocu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtComentario;
    private javax.swing.JTextField txtCredito;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtDebito;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextArea txtDetalles;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHechoPor;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNroDocu;
    // End of variables declaration//GEN-END:variables
}
