/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;


public class MovimientoTransacciones extends javax.swing.JFrame {
    
    private Integer secuenciaEditando = null;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MovimientoTransacciones.class.getName());

    /**
     * Creates new form MovimientoTransacciones
     */
    public MovimientoTransacciones() {
        initComponents();
        setLocationRelativeTo(null); // centrar

        // Debito / Credito mutuamente excluyentes
        txtDebitoLinea.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {
                debitoCambio();
            }
        });

        txtCreditoLinea.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {
                creditoCambio();
            }
        });
    }
    
    
    private void debitoCambio() {
        String debito = txtDebitoLinea.getText().trim();
        if (!debito.isEmpty()) {
            // si escribo débito, bloqueo crédito
            txtCreditoLinea.setText("");
            txtCreditoLinea.setEnabled(false);
        } else {
            // si borro débito, vuelvo a permitir crédito
            txtCreditoLinea.setEnabled(true);
        }
    }

    private void creditoCambio() {
        String credito = txtCreditoLinea.getText().trim();
        if (!credito.isEmpty()) {
            txtDebitoLinea.setText("");
            txtDebitoLinea.setEnabled(false);
        } else {
            txtDebitoLinea.setEnabled(true);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipoLinea = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNroDocu = new javax.swing.JTextField();
        cbTipoDocu = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHechoPor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnActualizarMonto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtComentario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnAgregarDetalle = new javax.swing.JButton();
        txtCuenta = new javax.swing.JTextField();
        lblNombreCuenta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDebitoLinea = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCreditoLinea = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalles = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Nro Documento");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Tipo Documento");

        txtNroDocu.addActionListener(this::txtNroDocuActionPerformed);

        cbTipoDocu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Factura", "Nota Debito", "Nota Credito" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Fecha");

        txtFecha.addActionListener(this::txtFechaActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Descripcion");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Hecho por");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Monto Total");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnActualizarMonto.setText("Actualizar monto");
        btnActualizarMonto.addActionListener(this::btnActualizarMontoActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtNroDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(141, 141, 141))
                            .addComponent(txtHechoPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cbTipoDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnActualizarMonto)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNroDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHechoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarMonto))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movimiento Transacciones");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Cuenta Contable");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Comentario");

        btnAgregarDetalle.setText("Agregar Detalle");
        btnAgregarDetalle.setToolTipText("");
        btnAgregarDetalle.addActionListener(this::btnAgregarDetalleActionPerformed);

        txtCuenta.addActionListener(this::txtCuentaActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Debito");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("Credito");

        tblDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDetalles);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDebitoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCreditoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarDetalle)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(txtDebitoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCreditoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAgregarDetalle))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCerrar.setBackground(new java.awt.Color(255, 51, 51));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtNroDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroDocuActionPerformed
        String nro = txtNroDocu.getText().trim();
        if (nro.isEmpty()) return;

        model.CabeceraTransaccion cab =
                data.CabeceraArchivo.buscarPorNumero(nro);

        if (cab == null) {
            // No existe, limpiar campos y permitir crear
            txtFecha.setText("");
            cbTipoDocu.setSelectedIndex(0);
            txtDescripcion.setText("");
            txtHechoPor.setText("");
            txtMonto.setText("");

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Documento no existe. Puede crearlo.",
                    "Información",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (cab.isStatusActualizacion()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Transacción ha sido actualizada (cerrada). No se puede modificar.",
                        "Información",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
            }
            // Mostrar datos
            txtFecha.setText(cab.getFechaDocu());
            // mapear tipoDocu numérico a texto
            switch (cab.getTipoDocu()) {
                case 1 -> cbTipoDocu.setSelectedItem("Factura");
                case 2 -> cbTipoDocu.setSelectedItem("Nota Débito");
                case 3 -> cbTipoDocu.setSelectedItem("Nota Crédito");
                default -> cbTipoDocu.setSelectedIndex(0);
            }
            txtDescripcion.setText(cab.getDescripcion());
            txtHechoPor.setText(cab.getHechoPor());
            txtMonto.setText(String.valueOf(cab.getMontoTransaccion()));
            cargarTablaDetalles(nro);
        }

    }//GEN-LAST:event_txtNroDocuActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
                                                  
        String nro = txtNroDocu.getText().trim();
        String fecha = txtFecha.getText().trim();
        String tipoTexto = (String) cbTipoDocu.getSelectedItem();
        String descripcion = txtDescripcion.getText().trim();
        String hechoPor = txtHechoPor.getText().trim();
        String montoTexto = txtMonto.getText().trim();

        if (nro.isEmpty() || fecha.isEmpty() || "Seleccione".equals(tipoTexto)
                || descripcion.isEmpty() || hechoPor.isEmpty() || montoTexto.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Todos los campos de cabecera son obligatorios.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int tipoDocu;
        if ("Factura".equals(tipoTexto)) {
            tipoDocu = 1;
        } else if ("Nota Débito".equals(tipoTexto)) {
            tipoDocu = 2;
        } else {
            tipoDocu = 3;
        }

        double monto;
        try {
            monto = Double.parseDouble(montoTexto);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El monto debe ser numérico.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        model.CabeceraTransaccion existente =
                data.CabeceraArchivo.buscarPorNumero(nro);

        String fechaActualizacion = fecha;   // por ahora usamos la misma
        boolean statusActualizacion = false; // aún no cerrada

        if (existente == null) {
            // Crear nueva
            model.CabeceraTransaccion nueva = new model.CabeceraTransaccion(
                    nro, fecha, tipoDocu, descripcion, hechoPor,
                    monto, fechaActualizacion, statusActualizacion);

            boolean ok = data.CabeceraArchivo.agregar(nueva);

            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Cabecera creada correctamente.",
                        "Información",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                btnAgregarDetalle.setEnabled(true);

            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Ya existe una cabecera con ese número.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Modificar existente (si aún no está cerrada)
            if (existente.isStatusActualizacion()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "La transacción ya fue actualizada/cerrada. No se puede modificar.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            model.CabeceraTransaccion modificada = new model.CabeceraTransaccion(
                    nro, fecha, tipoDocu, descripcion, hechoPor,
                    monto, fechaActualizacion, statusActualizacion);

            boolean ok = data.CabeceraArchivo.actualizar(modificada);

            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Cabecera modificada correctamente.",
                        "Información",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se pudo actualizar la cabecera.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDetalleActionPerformed
        String nro = txtNroDocu.getText().trim();

        if (nro.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe indicar un número de documento.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        model.CabeceraTransaccion cab =
                data.CabeceraArchivo.buscarPorNumero(nro);

        if (cab == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No puede agregar detalles porque el documento NO existe.\n"
                  + "Primero debe guardar la cabecera del documento.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            txtNroDocu.requestFocus();
            return;
        }
        
        String cuenta = txtCuenta.getText().trim();
        String debitoTxt = txtDebitoLinea.getText().trim();
        String creditoTxt = txtCreditoLinea.getText().trim();
        String comentario = txtComentario.getText().trim();

        if (nro.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe indicar un Nro de documento primero.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (cuenta.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe indicar la cuenta contable.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar que la cuenta exista en el catálogo
        model.CuentaContable cta = data.CuentaArchivo.buscarPorNumero(cuenta);
        if (cta == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La cuenta contable no existe en el catálogo.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            txtCuenta.requestFocus();
            return;
        }

        if (debitoTxt.isEmpty() && creditoTxt.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe indicar un monto en Débito o en Crédito.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double debito = 0.0;
        double credito = 0.0;

        // Solo uno de los dos debe tener valor
        if (!debitoTxt.isEmpty() && !creditoTxt.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Solo puede llenar Débito o Crédito, no ambos.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            if (!debitoTxt.isEmpty()) {
                debito = Double.parseDouble(debitoTxt);
            }
            if (!creditoTxt.isEmpty()) {
                credito = Double.parseDouble(creditoTxt);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Los montos deben ser numéricos.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (debito < 0 || credito < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Los montos no pueden ser negativos.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (debito == 0 && credito == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El monto debe ser mayor que cero.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Determinar secuencia (si usas edición, conserva tu lógica con secuenciaEditando)
        int secuencia;
        if (secuenciaEditando == null) {
            java.util.List<model.DetalleTransaccion> existentes =
                    data.DetalleArchivo.cargarPorDocumento(nro);
            secuencia = existentes.size() + 1;
        } else {
            secuencia = secuenciaEditando;
        }

        model.DetalleTransaccion det = new model.DetalleTransaccion(
                nro, secuencia, cuenta, debito, credito, comentario);

        boolean ok;
        if (secuenciaEditando == null) {
            ok = data.DetalleArchivo.agregar(det);
        } else {
            ok = data.DetalleArchivo.actualizar(det);
        }

        if (ok) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    (secuenciaEditando == null ? "Detalle agregado." : "Detalle actualizado."),
                    "Información",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            secuenciaEditando = null;
            cargarTablaDetalles(nro);

            txtCuenta.setText("");
            txtDebitoLinea.setText("");
            txtCreditoLinea.setText("");
            txtDebitoLinea.setEnabled(true);
            txtCreditoLinea.setEnabled(true);
            txtComentario.setText("");
            txtCuenta.requestFocus();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo guardar el detalle.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarDetalleActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaActionPerformed
        String cuenta = txtCuenta.getText().trim();
        if (cuenta.isEmpty()) {
            return;
        }

        model.CuentaContable cta = data.CuentaArchivo.buscarPorNumero(cuenta);

        if (cta == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La cuenta " + cuenta + " no existe en el catálogo.",
                    "Cuenta no encontrada",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            // limpiar y volver al campo
            txtCuenta.setText("");
            lblNombreCuenta.setText("");
            txtCuenta.requestFocus();
        } else {
            // Cuenta válida: puedes mostrar la descripción
            lblNombreCuenta.setText(cta.getDescripcion());

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Cuenta encontrada: " + cta.getDescripcion(),
                    "Cuenta válida",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // mover el foco al campo de débito
            txtDebitoLinea.requestFocus();
        }
    }//GEN-LAST:event_txtCuentaActionPerformed

    private void btnActualizarMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMontoActionPerformed
        String nro = txtNroDocu.getText().trim();

        if (nro.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe indicar un Nro de documento primero.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Buscar la cabecera existente
        model.CabeceraTransaccion cab =
                data.CabeceraArchivo.buscarPorNumero(nro);

        if (cab == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La cabecera del documento no existe. Guárdela primero.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Cargar detalles del documento
        java.util.List<model.DetalleTransaccion> detalles =
                data.DetalleArchivo.cargarPorDocumento(nro);

        if (detalles.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El documento no tiene detalles. No se puede calcular el monto.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double totalDebito = 0.0;
        double totalCredito = 0.0;

        for (model.DetalleTransaccion d : detalles) {
            totalDebito += d.getValorDebito();
            totalCredito += d.getValorCredito();
        }

        // Verificar que la transacción esté cuadrada
        if (Math.abs(totalDebito - totalCredito) > 0.001) { // tolerancia pequeña
            javax.swing.JOptionPane.showMessageDialog(this,
                    String.format("La transacción no está cuadrada.%nDébitos: %.2f  Créditos: %.2f",
                            totalDebito, totalCredito),
                    "Error de cuadratura",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Si está cuadrada, usamos el total de débitos como monto de la cabecera
        cab.setMontoTransaccion(totalDebito);

        // Opcional: actualizar fecha de actualización con la fecha de hoy
        String hoy = java.time.LocalDate.now().toString(); // yyyy-MM-dd
        cab.setFechaActualizacion(hoy);

        boolean ok = data.CabeceraArchivo.actualizar(cab);

        if (ok) {
            txtMonto.setText(String.valueOf(totalDebito));

            javax.swing.JOptionPane.showMessageDialog(this,
                    String.format("Monto de cabecera actualizado correctamente.%nMonto: %.2f", totalDebito),
                    "Información",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo actualizar la cabecera.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarMontoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MovimientoTransacciones().setVisible(true));
    }
    
    private void cargarTablaDetalles(String nroDocu) {
        java.util.List<model.DetalleTransaccion> lista =
                data.DetalleArchivo.cargarPorDocumento(nroDocu);

        String[] columnas = { "Secuencia", "Cuenta", "Débito", "Crédito", "Comentario" };

        javax.swing.table.DefaultTableModel modelo =
                new javax.swing.table.DefaultTableModel(columnas, 0) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false; // tabla solo lectura
                    }
                };

        for (model.DetalleTransaccion d : lista) {
            Object[] fila = {
                    d.getSecuencia(),
                    d.getCuentaContable(),
                    d.getValorDebito(),
                    d.getValorCredito(),
                    d.getComentario()
            };
            modelo.addRow(fila);
        }

        tblDetalles.setModel(modelo);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarMonto;
    private javax.swing.JButton btnAgregarDetalle;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbTipoDocu;
    private javax.swing.ButtonGroup grpTipoLinea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lblNombreCuenta;
    private javax.swing.JTable tblDetalles;
    private javax.swing.JTextField txtComentario;
    private javax.swing.JTextField txtCreditoLinea;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtDebitoLinea;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHechoPor;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNroDocu;
    // End of variables declaration//GEN-END:variables
}
