/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;


public class MovimientoTransacciones extends javax.swing.JFrame {
    
    private Integer secuenciaEditando = null;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MovimientoTransacciones.class.getName());

    /**
     * Creates new form MovimientoTransacciones
     */
    public MovimientoTransacciones() {
        initComponents();
        setLocationRelativeTo(null); // centrar
        
        tblDetalles.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent e) {
            if (e.getClickCount() == 2) { // doble clic
                int fila = tblDetalles.getSelectedRow();
                if (fila >= 0) {
                    // Datos de la tabla
                    int secuencia = Integer.parseInt(
                            tblDetalles.getValueAt(fila, 0).toString());
                    String cuenta = tblDetalles.getValueAt(fila, 1).toString();
                    double debito = Double.parseDouble(
                            tblDetalles.getValueAt(fila, 2).toString());
                    double credito = Double.parseDouble(
                            tblDetalles.getValueAt(fila, 3).toString());
                    String comentario = tblDetalles.getValueAt(fila, 4).toString();

                    // Guardamos la secuencia que se está editando
                    secuenciaEditando = secuencia;

                    // Llenamos el formulario de detalle
                    txtCuenta.setText(cuenta);
                    txtComentario.setText(comentario);
                    if (debito > 0) {
                        rbDebito.setSelected(true);
                        txtMontoLinea.setText(String.valueOf(debito));
                    } else {
                        rbCredito.setSelected(true);
                        txtMontoLinea.setText(String.valueOf(credito));
                    }
                }
            }
        }
    });
    }
    
    

    
    private void actualizarAreaDetalles(String nroDocu) {
    java.util.List<model.DetalleTransaccion> detalles =
            data.DetalleArchivo.cargarPorDocumento(nroDocu);

    StringBuilder sb = new StringBuilder();
    for (model.DetalleTransaccion d : detalles) {
        sb.append(String.format("%s | %d | %s | D: %.2f | C: %.2f | %s%n",
                d.getNroDoc(),
                d.getSecuencia(),
                d.getCuentaContable(),
                d.getValorDebito(),
                d.getValorCredito(),
                d.getComentario()));
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipoLinea = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNroDocu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbTipoDocu = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHechoPor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAgregarDetalle = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        txtComentario = new javax.swing.JTextField();
        txtMontoLinea = new javax.swing.JTextField();
        rbDebito = new javax.swing.JRadioButton();
        rbCredito = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movimiento Transacciones");

        jLabel2.setText("Nro Documento");

        txtNroDocu.addActionListener(this::txtNroDocuActionPerformed);

        jLabel3.setText("Fecha");

        txtFecha.addActionListener(this::txtFechaActionPerformed);

        jLabel4.setText("Tipo Documento");

        cbTipoDocu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Factura", "Nota Debito", "Nota Credito" }));

        jLabel5.setText("Descripcion");

        jLabel6.setText("Hecho por");

        jLabel7.setText("Monto Total");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        jLabel8.setText("Cuenta Contable");

        jLabel9.setText("Debito");

        jLabel10.setText("Credito");

        jLabel11.setText("Comentario");

        btnAgregarDetalle.setText("Agregar Detalle");
        btnAgregarDetalle.setToolTipText("");
        btnAgregarDetalle.addActionListener(this::btnAgregarDetalleActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        grpTipoLinea.add(rbDebito);
        rbDebito.addActionListener(this::rbDebitoActionPerformed);

        grpTipoLinea.add(rbCredito);

        tblDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDetalles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(txtNroDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(141, 141, 141))
                                    .addComponent(txtHechoPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbTipoDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                                .addComponent(btnGuardar)))))
                                .addGap(15, 15, 15))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbDebito)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbCredito)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(txtComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAgregarDetalle)
                                        .addGap(12, 12, 12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMontoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCerrar)
                                        .addGap(23, 23, 23)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNroDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHechoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(rbDebito)
                            .addComponent(rbCredito))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMontoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCerrar)))
                    .addComponent(btnAgregarDetalle))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtNroDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroDocuActionPerformed
        String nro = txtNroDocu.getText().trim();
        if (nro.isEmpty()) return;

        model.CabeceraTransaccion cab =
                data.CabeceraArchivo.buscarPorNumero(nro);

        if (cab == null) {
            // No existe, limpiar campos y permitir crear
            txtFecha.setText("");
            cbTipoDocu.setSelectedIndex(0);
            txtDescripcion.setText("");
            txtHechoPor.setText("");
            txtMonto.setText("");
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Documento no existe. Puede crearlo.",
                    "Información",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (cab.isStatusActualizacion()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Transacción ha sido actualizada (cerrada). No se puede modificar.",
                        "Información",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
            }
            // Mostrar datos
            txtFecha.setText(cab.getFechaDocu());
            // mapear tipoDocu numérico a texto
            switch (cab.getTipoDocu()) {
                case 1 -> cbTipoDocu.setSelectedItem("Factura");
                case 2 -> cbTipoDocu.setSelectedItem("Nota Débito");
                case 3 -> cbTipoDocu.setSelectedItem("Nota Crédito");
                default -> cbTipoDocu.setSelectedIndex(0);
            }
            txtDescripcion.setText(cab.getDescripcion());
            txtHechoPor.setText(cab.getHechoPor());
            txtMonto.setText(String.valueOf(cab.getMontoTransaccion()));
            cargarTablaDetalles(nro);
        }

    }//GEN-LAST:event_txtNroDocuActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
                                                  
        String nro = txtNroDocu.getText().trim();
        String fecha = txtFecha.getText().trim();
        String tipoTexto = (String) cbTipoDocu.getSelectedItem();
        String descripcion = txtDescripcion.getText().trim();
        String hechoPor = txtHechoPor.getText().trim();
        String montoTexto = txtMonto.getText().trim();

        if (nro.isEmpty() || fecha.isEmpty() || "Seleccione".equals(tipoTexto)
                || descripcion.isEmpty() || hechoPor.isEmpty() || montoTexto.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Todos los campos de cabecera son obligatorios.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int tipoDocu;
        if ("Factura".equals(tipoTexto)) {
            tipoDocu = 1;
        } else if ("Nota Débito".equals(tipoTexto)) {
            tipoDocu = 2;
        } else {
            tipoDocu = 3;
        }

        double monto;
        try {
            monto = Double.parseDouble(montoTexto);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El monto debe ser numérico.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        model.CabeceraTransaccion existente =
                data.CabeceraArchivo.buscarPorNumero(nro);

        String fechaActualizacion = fecha;   // por ahora usamos la misma
        boolean statusActualizacion = false; // aún no cerrada

        if (existente == null) {
            // Crear nueva
            model.CabeceraTransaccion nueva = new model.CabeceraTransaccion(
                    nro, fecha, tipoDocu, descripcion, hechoPor,
                    monto, fechaActualizacion, statusActualizacion);

            boolean ok = data.CabeceraArchivo.agregar(nueva);

            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Cabecera creada correctamente.",
                        "Información",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Ya existe una cabecera con ese número.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Modificar existente (si aún no está cerrada)
            if (existente.isStatusActualizacion()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "La transacción ya fue actualizada/cerrada. No se puede modificar.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            model.CabeceraTransaccion modificada = new model.CabeceraTransaccion(
                    nro, fecha, tipoDocu, descripcion, hechoPor,
                    monto, fechaActualizacion, statusActualizacion);

            boolean ok = data.CabeceraArchivo.actualizar(modificada);

            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Cabecera modificada correctamente.",
                        "Información",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se pudo actualizar la cabecera.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDetalleActionPerformed
        String nro = txtNroDocu.getText().trim();
        String cuenta = txtCuenta.getText().trim();
        String montoTexto = txtMontoLinea.getText().trim();
        String comentario = txtComentario.getText().trim();

        if (nro.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe indicar un Nro de documento primero.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (cuenta.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe indicar la cuenta contable.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar que la cuenta exista en el catálogo
        model.CuentaContable cta = data.CuentaArchivo.buscarPorNumero(cuenta);
        if (cta == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La cuenta contable no existe en el catálogo.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (montoTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe indicar un monto.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!rbDebito.isSelected() && !rbCredito.isSelected()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe seleccionar si el monto es Débito o Crédito.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double monto;
        try {
            monto = Double.parseDouble(montoTexto);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El monto debe ser numérico.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (monto == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El monto debe ser mayor que cero.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double debito = 0.0;
        double credito = 0.0;

        if (rbDebito.isSelected()) {
            debito = monto;
        } else {
            credito = monto;
        }

        // Determinar secuencia: cantidad de líneas + 1
        int secuencia;

        // ¿estamos editando o creando?
        if (secuenciaEditando == null) {
            // NUEVA línea
            java.util.List<model.DetalleTransaccion> existentes =
                    data.DetalleArchivo.cargarPorDocumento(nro);
            secuencia = existentes.size() + 1;
        } else {
            // EDITANDO una existente
            secuencia = secuenciaEditando;
        }

        model.DetalleTransaccion det = new model.DetalleTransaccion(
                nro, secuencia, cuenta, debito, credito, comentario);

        boolean ok;
        if (secuenciaEditando == null) {
            ok = data.DetalleArchivo.agregar(det);
        } else {
            ok = data.DetalleArchivo.actualizar(det);
        }


        if (ok) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Detalle agregado.",
                    "Información",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            cargarTablaDetalles(nro);
            txtCuenta.setText("");
            txtMontoLinea.setText("");
            txtComentario.setText("");
            rbDebito.setSelected(true);
            txtCuenta.requestFocus();
            
            secuenciaEditando = null; // terminamos edición

            cargarTablaDetalles(nro);
            // Aquí luego llamaremos a cargarTablaDetalles(nro)
            // cuando tengamos la tabla creada.
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo agregar el detalle.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarDetalleActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void rbDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDebitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDebitoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MovimientoTransacciones().setVisible(true));
    }
    
    private void cargarTablaDetalles(String nroDocu) {
        java.util.List<model.DetalleTransaccion> lista =
                data.DetalleArchivo.cargarPorDocumento(nroDocu);

        String[] columnas = { "Secuencia", "Cuenta", "Débito", "Crédito", "Comentario" };

        javax.swing.table.DefaultTableModel modelo =
                new javax.swing.table.DefaultTableModel(columnas, 0) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false; // tabla solo lectura
                    }
                };

        for (model.DetalleTransaccion d : lista) {
            Object[] fila = {
                    d.getSecuencia(),
                    d.getCuentaContable(),
                    d.getValorDebito(),
                    d.getValorCredito(),
                    d.getComentario()
            };
            modelo.addRow(fila);
        }

        tblDetalles.setModel(modelo);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDetalle;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbTipoDocu;
    private javax.swing.ButtonGroup grpTipoLinea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbCredito;
    private javax.swing.JRadioButton rbDebito;
    private javax.swing.JTable tblDetalles;
    private javax.swing.JTextField txtComentario;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHechoPor;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtMontoLinea;
    private javax.swing.JTextField txtNroDocu;
    // End of variables declaration//GEN-END:variables
}
